chapter15_4 : chapter15_4.o readline.o
	gcc -o chapter15_4 chapter15_4.o readline.o

chapter15_4.o : chapter15_4.c readline.h
	gcc -c chapter15_4.c

readline.o : readline.c readline.h
	gcc -c readline.c
